# Setup
title:        Microsoft Azure IoT Developer Kit
tagline:      Microsoft Azure IoT Developer Kit (a.k.a DevKit) is used to develop and prototype Internet of Things (IoT) solutions leveraging on Microsoft Azure services. It includes an Arduino compatible board with rich peripherals and sensors, an open-source board package and a fast growing mini solution catalog.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Microsoft
  url:        http://microsoft.github.io/azure-iot-developer-kit

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown