# Setup
title:        Microsoft Azure IoT Developer Kit
tagline:      Fast develop IoT app using Microsoft Azure
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Microsoft
  url:        http://microsoft.github.io/azure-iot-developer-kit

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown